!DEFINE YOUR POTENTIAL HERE
     MODULE POT2DER
       USE RKSUITE_90_PREC

       REAL(WP)::V_PHI_PHI
     END MODULE POT2DER


     SUBROUTINE POTENTIAL_POTENTIALPRIME(POTENTIAL_USED,POTENTIALPRIME,PHI_X)
       USE RKSUITE_90_PREC
       USE THEORY_PARAM
       USE PARAMETERS
       USE POT2DER
       IMPLICIT NONE

       REAL(WP),INTENT(IN)::PHI_X
       REAL(WP),INTENT(OUT)::POTENTIAL_USED,POTENTIALPRIME
       REAL(WP)::MASS,ALPHA,PHI0,DELTA_PHI 
       POTENTIAL_USED=0.0D0
       POTENTIALPRIME=0.0D0
       V_PHI_PHI=0.0D0
       MASS=PARAM_1
       ALPHA=PARAM_2
       PHI0=PARAM_3
       DELTA_PHI=PARAM_4
       
       
       
       POTENTIAL_USED=0.5D0*(PHI_X**2.0D0)*(MASS**(2.0D0))
       POTENTIAL_USED=POTENTIAL_USED*(1.0D0+ALPHA*TANH((PHI_X-PHI0)/DELTA_PHI))

       POTENTIALPRIME=(MASS**(2.0D0))*PHI_X*(1.0D0+(ALPHA*TANH((PHI_X-PHI0)/DELTA_PHI)))

       POTENTIALPRIME=POTENTIALPRIME+0.5D0*(MASS**2.0D0)*&
	&(PHI_X**2.0D0)*ALPHA/(DELTA_PHI*(COSH((PHI_X-PHI0)/DELTA_PHI))**2.0D0)

       V_PHI_PHI=(MASS**(2.0D0))+(ALPHA*MASS*MASS*TANH((PHI_X-PHI0)/DELTA_PHI))
       V_PHI_PHI=V_PHI_PHI+2.0D0*(MASS**2.0D0)*(PHI_X)*ALPHA/(DELTA_PHI*(COSH((PHI_X-PHI0)/DELTA_PHI))**2.0_WP)
       V_PHI_PHI=V_PHI_PHI-(MASS*MASS*PHI_X*PHI_X*ALPHA/(DELTA_PHI*DELTA_PHI))&
	&*TANH((PHI_X-PHI0)/DELTA_PHI)/(COSH((PHI_X-PHI0)/DELTA_PHI)*COSH((PHI_X-PHI0)/DELTA_PHI))
    
     
     END SUBROUTINE POTENTIAL_POTENTIALPRIME
