! THE BACKGROUND EQUATIONS
       FUNCTION BACKGROUND(XB,YB)
         USE RKSUITE_90_PREC
         USE PARAMETERS
         USE THEORY_PARAM
         USE INTERFACING, ONLY:POTENTIAL_POTENTIALPRIME
         IMPLICIT NONE
         REAL(WP), INTENT(IN) :: XB
         REAL(WP), DIMENSION(:), INTENT(IN) :: YB
         REAL(KIND=WP), DIMENSION(SIZE(YB)) :: BACKGROUND
         REAL(WP)::VB,V_PHIB


         !------------------------BACKGROUND EQUATION-------------------------------


         CALL  POTENTIAL_POTENTIALPRIME(VB,V_PHIB,YB(1))


         BACKGROUND(1)=YB(2)
         BACKGROUND(2)=-(3.0_WP-0.5_WP*(YB(2)**2.0_WP))*YB(2)-(6.0_WP-(YB(2)**2.0_WP))*V_PHIB/(2.0_WP*VB)

       END FUNCTION BACKGROUND
