! HERE THE SUB-HUBBLE PERIOD FOR EACH MODE IS DETERMINED
SUBROUTINE FIND_NIC(KMODE)
  USE RKSUITE_90_PREC
  USE PARAMETERS
  USE BACKGROUND_PATH
  USE STOREK

  IMPLICIT NONE

  REAL(WP)::KMODE,TEMP,EPSILON1

  INTEGER::EFOLD
  LOGICAL::NIC_NOTFOUND

  NIC_NOTFOUND=.TRUE.

  

  EPSILON1=(KMODE/(NIC_COND*AI*dEXP(EF(1)))-HUBBLE(1))

  NIC_SOLUTION_REGION1:IF(EPSILON1>0.0_WP) THEN
     NIC_LOOP1: DO EFOLD=2,ESEARCH
        TEMP=(KMODE/(NIC_COND*AI*dEXP(EF(EFOLD)))-HUBBLE(EFOLD))
        EIC=EFOLD
        NIC=EF(EIC)

        IF(TEMP<0.0_WP) THEN
           NIC_NOTFOUND=.FALSE.
           EXIT
        END IF
     END DO NIC_LOOP1
  END IF NIC_SOLUTION_REGION1


  NIC_SOLUTION_REGION2:IF(EPSILON1<0.0_WP) THEN
     NIC_LOOP2: DO EFOLD=2,ESEARCH
        TEMP=(KMODE/(NIC_COND*AI*dEXP(EF(EFOLD)))-HUBBLE(EFOLD))
        EIC=EFOLD
        NIC=EF(EIC)
        IF(TEMP>0.0_WP) THEN
           NIC_NOTFOUND=.FALSE.
           EXIT
        END IF
     END DO NIC_LOOP2
  END IF NIC_SOLUTION_REGION2
  


  IF(NIC_NOTFOUND) STOP 'NIC NOT FOUND:MAYBE OUT OF THE RANGE'
END SUBROUTINE FIND_NIC
