!MODULE TO FIND INITIAL CONDITION
MODULE INITIATION
  USE RKSUITE_90_PREC



REAL(WP)::PHI_IC,PHID_IC,PHIDD_IC,A_INI,H_IC,Z_INI,R_INI,RPRIME_RE,RPRIME_IM

END MODULE INITIATION


SUBROUTINE INITIAL_COND(KMODE)
  USE RKSUITE_90_PREC
  
  USE PARAMETERS
  USE BACKGROUND_PATH
  USE STOREK 
  USE INITIATION
  IMPLICIT NONE


  REAL(WP)::KMODE
 

  
  
  !======INITIAL CONDITION FOR CURVATURE PERTURBATION EVALUATION======
  
  PHI_IC=PHI(EIC)
  
  PHID_IC=PHID(EIC)
  
  PHIDD_IC=PHIDD(EIC)
       
  
  A_INI=AI*dEXP(EF(EIC))
  H_IC=HUBBLE(EIC)
  Z_INI=A_INI*PHID_IC
  
  
  R_INI=(1.0_wp/(dSQRT(2.0_wp*KMODE)))/Z_INI!THIS IS THE INITIAL VALUE OF THE RK
  RPRIME_RE=-R_INI*((PHIDD_IC/PHID_IC)+1.0_wp)
  RPRIME_IM=-dSQRT(KMODE/2.0_wp)/(A_INI*H_IC*Z_INI)
 



END SUBROUTINE INITIAL_COND
