!INTERFACES OTHER ROUTINES
MODULE INTERFACING
  USE RKSUITE_90_PREC

  INTERFACE
     SUBROUTINE POTENTIAL_POTENTIALPRIME(POTENTIAL_USED,POTENTIALPRIME,PHI_X)
     USE RKSUITE_90_PREC

       IMPLICIT NONE

       REAL(WP),INTENT(IN)::PHI_X
       REAL(WP),INTENT(OUT)::POTENTIAL_USED,POTENTIALPRIME
     END SUBROUTINE POTENTIAL_POTENTIALPRIME
  END INTERFACE


  INTERFACE
     SUBROUTINE BACKGROUND_VALUE
      USE RKSUITE_90_PREC
       IMPLICIT NONE

     END SUBROUTINE BACKGROUND_VALUE
  END INTERFACE

  INTERFACE
     SUBROUTINE FIND_NIC(KMODE)
       USE RKSUITE_90_PREC

       IMPLICIT NONE

       REAL(WP)::KMODE

     END SUBROUTINE FIND_NIC
    END INTERFACE

    INTERFACE
       
       SUBROUTINE FIND_SHS(KMODE)
         USE RKSUITE_90_PREC

         IMPLICIT NONE
         
         REAL(WP)::KMODE

         
       END SUBROUTINE FIND_SHS

    END INTERFACE
    INTERFACE
      SUBROUTINE DOTPRODUCT(K1K2,K2K3,K3K1,K1,K2,K3)
        USE RKSUITE_90_PREC

        IMPLICIT NONE

        REAL(WP), INTENT(IN)::K1,K2,K3
        REAL(WP), INTENT(OUT)::K1K2,K2K3,K3K1
      END SUBROUTINE DOTPRODUCT
    END INTERFACE
    
    INTERFACE
       SUBROUTINE INITIAL_COND(KMODE)
         USE RKSUITE_90_PREC
 
         IMPLICIT NONE
         
         REAL(WP)::KMODE
       END SUBROUTINE INITIAL_COND
    END INTERFACE
    INTERFACE
	FUNCTION CURV_PERT(T,Y)
	  USE RKSUITE_90_PREC, ONLY:WP
	  REAL(KIND=WP), INTENT(IN) :: T                                 !INDEP!
	  REAL(KIND=WP), DIMENSION(:), INTENT(IN) :: Y                   !DEP!
	  REAL(KIND=WP), DIMENSION(SIZE(Y,1)) :: CURV_PERT                       !DEP!
     END FUNCTION CURV_PERT
    END INTERFACE
    INTERFACE

      FUNCTION BACKGROUND(XB,YB)
         USE RKSUITE_90_PREC
         IMPLICIT NONE
         REAL(WP), INTENT(IN) :: XB
         REAL(WP), DIMENSION(:), INTENT(IN) :: YB
         REAL(KIND=WP), DIMENSION(SIZE(YB)) :: BACKGROUND

      END FUNCTION BACKGROUND

    END INTERFACE
  END MODULE INTERFACING
