!MODULE TO  STORE AND PASS VALUES
MODULE STOREK
  USE RKSUITE_90_PREC
  IMPLICIT NONE
  REAL(WP)::NIC
  REAL(WP)::NSHS
  INTEGER::EIC
END MODULE STOREK

MODULE MODESTORE
  USE RKSUITE_90_PREC
  IMPLICIT NONE
  REAL(WP)::MODEK1,MODEK2,MODEK3,eps2
  LOGICAL::RL_INTEGRATION,CMPLX_INTEGRATION,SAVE_RK_NEND
  COMPLEX(WP)::RK1_NEND,RK1_PRIME_NEND,RK2_NEND,RK2_PRIME_NEND,RK3_NEND,RK3_PRIME_NEND
  REAL(WP)::k1dotk2,k2dotk3,k3dotk1
END MODULE MODESTORE

MODULE ODE_K
  USE RKSUITE_90_PREC
  IMPLICIT NONE
  REAL(WP)::MODEK
END MODULE ODE_K

MODULE FNLTERM
  USE RKSUITE_90_PREC
  IMPLICIT NONE
  INTEGER::TERM
  REAL(WP)::FNLFACTOR
  logical::equilateral,isosceles,scalene
END MODULE FNLTERM
