!DEFINE YOUR POTENTIAL HERE
     MODULE POT2DER
       USE RKSUITE_90_PREC

       REAL(WP)::V_PHI_PHI
     END MODULE POT2DER


     SUBROUTINE POTENTIAL_POTENTIALPRIME(POTENTIAL_USED,POTENTIALPRIME,PHI_X)
       USE RKSUITE_90_PREC
       USE THEORY_PARAM
       USE PARAMETERS
       USE POT2DER
       IMPLICIT NONE

       REAL(WP),INTENT(IN)::PHI_X
       REAL(WP),INTENT(OUT)::POTENTIAL_USED,POTENTIALPRIME
       REAL(WP)::MASS,LAMBDA,PHI_0
 
       POTENTIAL_USED=0.0_WP
       POTENTIALPRIME=0.0_WP
       V_PHI_PHI=0.0_WP

       
       MASS=PARAM_1
       PHI_0=PARAM_2
       
       LAMBDA=(2.0_WP)*(MASS**2.0_WP)/((NN-1.0_WP)*(PHI_0**(2.0_WP*(NN-2.0_WP))))

       POTENTIAL_USED=0.5_WP*(PHI_X**2.0_WP)*MASS**(2.0_WP)
       POTENTIAL_USED=POTENTIAL_USED+(LAMBDA/4.0_WP)*(PHI_X**(2.0_WP*(NN-1.0_WP)))
       POTENTIAL_USED=POTENTIAL_USED-(MASS*DSQRT(2.0_WP*LAMBDA*(NN-1.0_WP))/NN)*(PHI_X**NN)
       POTENTIALPRIME=(((MASS**(2.0_WP))*PHI_X)-((PHI_X**(NN-1.0_WP))*MASS*DSQRT(2.0_WP*LAMBDA*(NN-1.0_WP))) &
	&+((PHI_X**(2.0_WP*NN-3.0_WP))*2.0_WP*(LAMBDA/4.0_WP)*(NN-1.0_WP)))

     
       V_PHI_PHI=(MASS*MASS) -((PHI_X**(NN-2.0_WP))*MASS*(NN-1.0_WP)*DSQRT(2.0_WP*LAMBDA*(NN-1.0_WP))) &
	+((PHI_X**(2.0_WP*NN-4.0_WP))*2.0_WP*(LAMBDA/4.0_WP)*(NN-1.0_WP)*(2.0D0*NN-3.0_WP))

       
       
           
     
     END SUBROUTINE POTENTIAL_POTENTIALPRIME
