! MODEL PARAMETERS

MODULE PARAMETERS
  USE RKSUITE_90_PREC

  REAL(WP)::INITIALPHI

  REAL(WP)::INITIALPHIDOT

  REAL(WP)::NIC_COND

  REAL(WP),PARAMETER::NSHS_COND=1.0D5

  REAL(WP),PARAMETER::NF=80.0_WP

  REAL(WP),PARAMETER::NI=0.0_WP

  REAL(WP)::PIVOTK

  REAL(WP)::N_pivot

  INTEGER,PARAMETER::BGSTEPS=50000
END MODULE PARAMETERS
